-- Insertar datos en la tabla patologias
INSERT INTO patologias (nombre, descripcion) VALUES
('Hipertensión', 'Elevada presión arterial.'),
('Diabetes Tipo 1', 'Enfermedad crónica en la que el páncreas produce poca o ninguna insulina.'),
('Asma', 'Enfermedad inflamatoria crónica de las vías respiratorias.'),
('Migraña', 'Dolor de cabeza intenso y pulsátil.'),
('Artritis Reumatoide', 'Enfermedad inflamatoria crónica que afecta las articulaciones.'),
('EPOC', 'Enfermedad pulmonar obstructiva crónica que causa dificultad para respirar.'),
('Depresión', 'Trastorno mental que causa un sentimiento persistente de tristeza.'),
('Insuficiencia Cardíaca', 'Condición en la que el corazón no bombea sangre tan bien como debería.'),
('Gastritis', 'Inflamación del revestimiento del estómago.'),
('Anemia', 'Condición en la que no hay suficientes glóbulos rojos saludables para transportar oxígeno.'),
('Hepatitis B', 'Infección hepática grave causada por el virus de la hepatitis B.'),
('Psoriasis', 'Enfermedad autoinmune que causa parches de piel gruesos y escamosos.'),
('Epilepsia', 'Trastorno neurológico que provoca convulsiones recurrentes.'),
('Cáncer de Piel', 'Crecimiento anormal de las células de la piel.'),
('Esclerosis Múltiple', 'Enfermedad del sistema nervioso central que interrumpe el flujo de información dentro del cerebro y entre el cerebro y el cuerpo.');

INSERT INTO especialidades (nombre) VALUES
('Cardiología'),
('Neurología'),
('Pediatría'),
('Dermatología'),
('Ginecología'),
('Oftalmología'),
('Traumatología'),
('Anestesiología'),
('Oncología'),
('Psiquiatría'),
('Radiología'),
('Endocrinología'),
('Nefrología'),
('Hematología'),
('Reumatología'),
('Cirugía General'),
('Urología');

INSERT INTO empleado (
  ced_empleado,
  nombres,
  apellidos,
  telefono_celular,
  contrasena,
  rol
) VALUES (
  12345678,
  'Pedro',
  'Gonzalez Lopez',
  '04141234567',
  '12341234',
  'rol1'
);

INSERT INTO estados (nombre_estado) VALUES
('Amazonas'),
('Anzoátegui'),
('Apure'),
('Aragua'),
('Barinas'),
('Bolívar'),
('Carabobo'),
('Cojedes'),
('Delta Amacuro'),
('Distrito Capital'),
('Falcón'),
('Guárico'),
('Lara'),
('La Guaira'),
('Mérida'),
('Miranda'),
('Monagas'),
('Nueva Esparta'),
('Portuguesa'),
('Sucre'),
('Táchira'),
('Trujillo'),
('Yaracuy'),
('Zulia');


INSERT INTO ciudades (nombre_ciudad, cod_estado) VALUES
('San Fernando de Atabapo', '1'),
('Maroa', '1'),
('San Carlos de Río Negro', '1'),
('La Esmeralda', '1'),
('San Juan de Manapiare', '1'),
('San Juan de Payara', '1'),
('Guacharaquero', '1'),
('Samariapo', '1'),
('Mavaca', '1'),
('Barcelona', '2'),
('Puerto', '2'),
('Lechería', '2'),
('El Tigre', '2'),
('Anaco', '2'),
('Cantaura', '2'),
('Clarines', '2'),
('Píritu', '2'),
('Aragua de Barcelona', '2'),
('San Mateo', '2'),
('Santa Ana', '2'),
('El Tigrito', '2'),
('Pariaguán', '2'),
('Guanape', '2'),
('Boca de Uchire', '2'),
('Onoto', '2'),
('Puerto Píritu', '2'),
('San Tomé', '2'),
('San Fernando de Apure', '3'),
('Guasdualito', '3'),
('Elorza', '3'),
('Achaguas', '3'),
('Biruaca', '3'),
('Bruzual', '3'),
('Mantecal', '3'),
('Guacharaquero', '3'),
('La Victoria', '3'),
('San Juan de Payara', '3'),
('Palmarito', '3'),
('Puerto Páez', '3'),
('Maracay', '4'),
('Turmero', '4'),
('La Victoria', '4'),
('El Limón', '4'),
('Cagua', '4'),
('Villa de Cura', '4'),
('San Mateo', '4'),
('Santa Cruz de Aragua', '4'),
('El Consejo', '4'),
('Tejerías', '4'),
('San Casimiro', '4'),
('Colonia Tovar', '4'),
('Las Delicias', '4'),
('El Castaño', '4'),
('Choroní', '4'),
('Ocumare de la Costa', '4'),
('Magdaleno', '4'),
('Camatagua', '4'),
('Barbacoas', '4'),
('San Sebastián de los Reyes', '4'),
('Barinas', '5'),
('Barinitas', '5'),
('Socopó', '5'),
('Santa Bárbara de Barinas', '5'),
('Sabaneta', '5'),
('Ciudad Bolivia', '5'),
('El Cantón', '5'),
('Obispos', '5'),
('Libertad de Barinas', '5'),
('San Silvestre', '5'),
('Altamira de Cáceres', '5'),
('Torunos', '5'),
('Barrancas', '5'),
('La Caramuca', '5'),
('Punta Gorda', '5'),
('Palacio Fajardo', '5'),
('Upata', '6'),
('Tumeremo', '6'),
('El Callao', '6'),
('Guasipati', '6'),
('Caicara del Orinoco', '6'),
('Santa Elena de Uairén', '6'),
('El Dorado', '6'),
('Maripa', '6'),
('La Paragua', '6'),
('Kumarakapay', '6'),
('Las Claritas', '6'),
('Matanzas', '6'),
('Ciudad Piar', '6'),
('El Manteco', '6'),
('Pijiguaos', '6'),
('Valencia', '7'),
('Puerto Cabello', '7'),
('Guacara', '7'),
('San Joaquín', '7'),
('Mariara', '7'),
('Tocuyito', '7'),
('Naguanagua', '7'),
('Bejuma', '7'),
('Morón', '7'),
('Montalbán', '7'),
('Los Guayos', '7'),
('Guigue', '7'),
('Miranda', '7'),
('San Diego', '7'),
('Canoabo', '7'),
('San Carlos', '8'),
('Tinaquillo', '8'),
('El Baño de las Lajas', '8'),
('Valle de la Pascua', '8'),
('Acarigua', '8'),
('Las Vegas', '8'),
('Cabrera', '8'),
('Macapo', '8'),
('Río Claro', '8'),
('Zamora', '8'),
('Las Tejerías', '8'),
('La Sabanita', '8'),
('Chaguaramas', '8'),
('Tucupita', '9'),
('Casacoima', '9'),
('Pedernales', '9'),
('Caracas', '10'),
('El Junquito', '10'),
('La Dolorita', '10'),
('Macaray', '10'),
('Caraballeda', '10'),
('Coro', '11'),
('Dabajuro', '11'),
('Churuguara', '11'),
('Punto Fijo', '11'),
('Adícora', '11'),
('Maroa', '11'),
('La Vela de Coro', '11'),
('San Juan de los Morros', '12'),
('Valle de la Pascua', '12'),
('El Sombrero', '12'),
('Calabozo', '12'),
('Las Mercedes', '12'),
('San José de Guaribe', '12'),
('Barquisimeto', '13'),
('Cabudare', '13'),
('Carora', '13'),
('Duaca', '13'),
('El Tocuyo', '13'),
('Quibor', '13'),
('La Guaira', '14'),
('Caraballeda', '14'),
('Macuto', '14'),
('Naiguatá', '14'),
('Mérida', '15'),
('El Vigía', '15'),
('Tovar', '15'),
('Nueva Bolivia', '15'),
('Tabay', '15'),
('Los Teques', '16'),
('Guarenas', '16'),
('Guatire', '16'),
('Cúa', '16'),
('Charallave', '16'),
('Ocumare del Tuy', '16'),
('San Antonio de los Altos', '16'),
('Maturín', '17'),
('Punta de Mata', '17'),
('Cumaná', '17'),
('Caripito', '17'),
('La Cruz de los Morros', '17'),
('Porlamar', '18'),
('La Asunción', '18'),
('Juan Griego', '18'),
('Santa Ana', '18'),
('Guanare', '19'),
('Acarigua', '19'),
('Guanarito', '19'),
('Tucupido', '19'),
('Altagracia de Orituco', '19'),
('Cumaná', '20'),
('Carúpano', '20'),
('Yaguaraparo', '20'),
('Río Caribe', '20'),
('Casanay', '20'),
('San Cristóbal', '21'),
('La Grita', '21'),
('Táriba', '21'),
('San Antonio del Táchira', '21'),
('Ureña', '21'),
('Trujillo', '22'),
('Valera', '22'),
('Boconó', '22'),
('El Dividive', '22'),
('Carache', '22'),
('San Felipe', '23'),
('Chivacoa', '23'),
('Aroa', '23'),
('Yaritagua', '23'),
('Maracaibo', '24'),
('San Francisco', '24'),
('Ciudad Ojeda', '24'),
('La Villa del Rosario', '24'),
('Tía Juana', '24'),
('Machiques', '24'),
('Santa Bárbara del Zulia', '24');




